# tap
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'

# bin
brew 'mackup'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-git-prompt'
brew 'tmux'
brew 'coreutils'
brew 'tree'
brew 'mas'
brew 'wget'
brew 'vim'

# utils
cask 'alfred'
cask 'bettertouchtool'
cask 'amazon-drive'
cask 'google-drive'
cask 'licecap'
cask 'skype'
cask 'slack'
cask 'vlc'
cask 'webtorrent'
cask 'screenflow'
cask 'vysor'
cask 'divvy'
cask 'kid3'
cask 'divvy'
cask 'openemu'
cask 'sip'
cask 'disk-inventory-x'
cask 'spotify'
cask 'gyazo'

# browsers
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'chromium'
cask 'safari-technology-preview'
cask 'firefox'
cask 'firefox-beta' # error
cask 'firefoxdeveloperedition' # error
cask 'firefoxnightly'
cask 'torbrowser'

# development
cask 'docker'
cask 'iterm2'
cask 'android-studio'
cask 'android-file-transfer'
cask 'visual-studio-code'
cask 'java'
cask 'devdogs'
brew 'go'
cask 'imagealpha'
cask 'imageoptim'

# fonts
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-code-pro-for-powerline'
cask 'font-fira-code'
cask 'font-fira-sans'
cask 'font-fira-mono'
cask 'font-fira-mono-for-powerline'
